// <auto-generated />
namespace Vidly.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class EdicionMoviesAgregadasreferenciasatablaGenre : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EdicionMoviesAgregadasreferenciasatablaGenre));
        
        string IMigrationMetadata.Id
        {
            get { return "201709242228253_Edicion Movies - Agregadas referencias a tabla Genre"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
