// <auto-generated />
namespace Vidly.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DetecciondeCambiosresidualesleerdentroparamasdetalles : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DetecciondeCambiosresidualesleerdentroparamasdetalles));
        
        string IMigrationMetadata.Id
        {
            get { return "201710040012373_Deteccion de Cambios residuales - leer dentro para mas detalles"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
