// <auto-generated />
namespace Vidly.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class EdTabMoviesBorradoColumnaAgregadaporerror : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EdTabMoviesBorradoColumnaAgregadaporerror));
        
        string IMigrationMetadata.Id
        {
            get { return "201709242234358_Ed. Tab. Movies - Borrado Columna Agregada por error "; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
